### ISSUE TITLE
When reversed landed cost - stock move not reverse. (v.3.0 AES)

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#10]
1.When reversed landed cost - stock move not reverse.
2.For Journal Entry reversed, Narration : should be default “Reversed - Landed Cost LA-1510002”

https://docs.google.com/document/d/1qKBMbsuSNZ8t9Y5OD5E5Xub4D-IUPo7dA4l8l9E2YWM/edit

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/541479df3786fc64cbf7f7fc0fd57d5a6ef9fc87
