### ISSUE TITLE
Journal entry from payment should not edit directly

### ISSUE THREAD

**Issue by songpon** [nfco/netforce#126]
Standard process
1. Payment validate
2. Journal entry created
3. wants to change date
4. Cancel Payment  ( entry revert)
5. set payment to draft
6. validate again

User will not edit Journal entry directly

**Comment by Rattanawan-t** [comment]
Now, some customer they need to edit directly from journal entry.
Example : They key petty cash in Direct Payment and edit journal entry for enter supplier name to link Tax report. (in case they have many supplier invoice per one petty cash clearing)
