### ISSUE TITLE
when export csv for invoice or payment the filed "Contact" should be Contact Code not Contact Name

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#13]
For V.3 when export csv for invoice or payment the filed "Contact" should be Contact Code not Contact Name since the code field is not required and hard for small company to handle this.

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/5bdd7f55b7e901ec2cd00b6b7170e35fe49781b2
