### ISSUE TITLE
Can't run "Depreciation" 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#14]
error : unsupported operand type(s) for -=: 'Decimal' and 'float'

![image](https://cloud.githubusercontent.com/assets/14918821/10629768/f0c8d1ce-77fb-11e5-82d0-2af365b2f5cf.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/e3fc7007b61f81c859cfe6cc5a6e2770deaec59b
