### ISSUE TITLE
Date format to Buddhist Date

### ISSUE THREAD

**Issue by watcharapon** [nfco/netforce#143]
Once user changes the Date format to Buddhist Date (Main Menu > General > General > Organization Settings), system show the date correctly as you can see in the Date field below. But for the Date Picking (Calendar), system still show in Christian Date.

![calendar1 1](https://cloud.githubusercontent.com/assets/4704545/12289515/8f80ae32-ba0e-11e5-9bda-4ceec3956d7d.png)

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/ce29a590ec08b4543e15abdebc16544aa0f575b1
