### ISSUE TITLE
Imported COA type Equity it's changed to type Asset in list page and show type is blank when click to account code

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#15]
![image](https://cloud.githubusercontent.com/assets/14918821/10657069/466ee276-78b0-11e5-8b85-e2244faf648e.png)

![image](https://cloud.githubusercontent.com/assets/14918821/10657028/0ad484be-78b0-11e5-8001-a45c376e7702.png)

**Comment by songpon** [comment]
reopen if it still not working
