### ISSUE TITLE
Consolidate Accounting Report for Multi-Company

### ISSUE THREAD

**Issue by sudaratnok** [nfco/netforce#162]
When Run report on the parent company, there are some Accounting Report doesn't group the same account to one account from the different company. But some report group the same account to one account. The reports that has this problem are the list below:
1. Trial Balance
2. Trial Balance Details
3. Tax Summary
4. Cash Flow Statements
5. General Ledger Details
6. General Ledger Summary

Example of trial balance report that has this problem
![_-_2016-01-27_13 46 08](https://cloud.githubusercontent.com/assets/14918871/12606223/1fd5f8ee-c4fe-11e5-8c81-75b175ba1090.png)

**Comment by nf-dj** [comment]
![tb1](https://cloud.githubusercontent.com/assets/14906023/17516375/14a10816-5e68-11e6-916f-ce01f922b7cb.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/38aa36ab6f64b8474c85db272c0db241d461c48b
