### ISSUE TITLE
when change company data Organization Setting isn't change for Multi-Company

### ISSUE THREAD

**Issue by narathipve** [nfco/netforce#163]
step 1.
![selection_082](https://cloud.githubusercontent.com/assets/15605786/12607482/e384c6a4-c507-11e5-93dc-0f345fd84dbf.png)

step 2. 

![selection_083](https://cloud.githubusercontent.com/assets/15605786/12607496/f9be9364-c507-11e5-82e6-0e0cc4fdda2a.png)

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/842d2d350bc7b813eaac930c4c5d80f365310e8c
