### ISSUE TITLE
when make GR from PO amount not include Discount amt. 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#17]
when make GR from PO amount not include Discount amt. 

![image](https://cloud.githubusercontent.com/assets/14918821/10749959/bf518ea0-7ca2-11e5-9a14-9aa7307a1f0e.png)

![image](https://cloud.githubusercontent.com/assets/14918821/10749971/e1d69ef2-7ca2-11e5-811b-ddcfdac114b3.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/66cf06478f96f73b079c65b24b3a4a340d6015b3
