### ISSUE TITLE
Add Tab "Other Info" for Debit note invoice AR and AP

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#177]
Because some customer they have different sequence number for Debit Note invoice.
![image](https://cloud.githubusercontent.com/assets/14918821/12838064/9828a356-cbfb-11e5-8c03-6742d0590142.png)

![image](https://cloud.githubusercontent.com/assets/14918821/12838079/be2d68e8-cbfb-11e5-949f-e8ecbcd53a5c.png)

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/7a42754382a3240e9b96d51200a1bd0748d7813f
