### ISSUE TITLE
Error When Allocate amount Landed Cost

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#19]
Error : unsupported operand type(s) for *: 'NoneType' and 'Decimal'
![image](https://cloud.githubusercontent.com/assets/14918821/10752153/2dc5b65c-7cb9-11e5-8283-255084fb9177.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/cf4f82823839170f279fa2480d3a326ef5e255d1
