### ISSUE TITLE
Ref to issue  #162: Consolidate Amount in Trial Balance Report is not correct

### ISSUE THREAD

**Issue by sudaratnok** [nfco/netforce#206]
Ref Issue #162 

After I tested this issue. Trial Balance report has incorrect consolidated amount in every company

Amount in Chart Of account
![_-_2016-03-01_11 52 00](https://cloud.githubusercontent.com/assets/14918871/13424675/d1b784f6-dfd4-11e5-8b89-c5eb182b4ef8.png)

Amount in Trial Balance

![_-_2016-03-01_11 51 42](https://cloud.githubusercontent.com/assets/14918871/13425510/d5332b9e-dfd9-11e5-918e-ad454106be5a.png)

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/38aa36ab6f64b8474c85db272c0db241d461c48b
