### ISSUE TITLE
when edit product and save always error "Failed to write record (concurrent access), please reload the page"

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#207]
when we click the link from other record to the product page, after edit and save there is an error but if go can click product item directly after changed something and save it's working fine.

![image](https://cloud.githubusercontent.com/assets/14918821/13449632/0a6de58e-e060-11e5-8361-2a550f9f2127.png)

**Comment by nf-dj** [comment]
can not replicate (test on plr db, was working)
