### ISSUE TITLE
Depreciation Schedule Report

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#238]
When Run Depreciation Report in Jan-Dec'2015 but the year 2016 is also included.

![image](https://cloud.githubusercontent.com/assets/14918821/14009900/d5c59fa6-f1c2-11e5-8974-dd41455f710d.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/91d2a2410cedd735c213dc463edbe6d2a5686a5c
