### ISSUE TITLE
list view invisible=True not working

### ISSUE THREAD

**Issue by songpon** [nfco/netforce#244]
![image](https://cloud.githubusercontent.com/assets/2561193/14073545/2c34051a-f4f4-11e5-9bf1-3a1f3725bd01.png)

**Comment by watcharapon** [comment]
fix: https://github.com/nfco/netforce/pull/246/commits/10725cef351345b9ed17be0628585444248fa98d
please mere request: https://github.com/nfco/netforce/pull/246
