### ISSUE TITLE
Function "Search" Landed Cost it's not working 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#26]
Note : should be can search GR number also.
![image](https://cloud.githubusercontent.com/assets/14918821/10754976/a2725884-7ccd-11e5-9d92-3ae081905e9b.png)

**Comment by nf-dj** [comment]
https://github.com/nfco/netforce/commit/a4dd8ca65fadad4e3df0e18d8cc2e5a3fbbabedc
