### ISSUE TITLE
improve SO->GI and PO->GR (prod categ accounts)

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#270]
Cost of goods sold in product categories and in the product it's not work when validate inventory transaction.

**Comment by Rattanawan-t** [comment]
Costing Method at Product Categ (tab Account) it's doesn't work

**Comment by Rattanawan-t** [comment]
Purchase Account at Product Categ. it's not link to Purchase Invoice.

**Comment by Rattanawan-t** [comment]
Need to put Stock input account in product and Product categorie (and also in the location and it's already there)

**Comment by nf-dj** [comment]
Stock in/out accounts were removed several months ago. (replaced by cogs account)
Need example use case if want to add back.

**Comment by nf-dj** [comment]
cogs account in prod categ was fixed here: https://github.com/nfco/netforce/commit/dc03fa7a3f2c7ac4b455520373346782dd785616
