### ISSUE TITLE
Profit and Loss report, account view is not sorted by account code currently.

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#353]
![image](https://cloud.githubusercontent.com/assets/14918821/16837061/38e2fd06-49eb-11e6-874d-ffa204689bee.png)

![image](https://cloud.githubusercontent.com/assets/14918821/16837168/c7c6f504-49eb-11e6-89a4-0dc429a059d6.png)

**Comment by nf-dj** [comment]
fixed

**Comment by nf-dj** [comment]
![aes1](https://cloud.githubusercontent.com/assets/14906023/16840014/925ca286-49fc-11e6-9197-d92a1a5e3963.png)

**Comment by Rattanawan-t** [comment]
Thank you
