### ISSUE TITLE
Error : Nothing left to invoice, can not partial invoice from PO 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#37]
![image](https://cloud.githubusercontent.com/assets/14918821/10809750/29e9cbd0-7e2c-11e5-8c55-ad1ed571abd4.png)

![image](https://cloud.githubusercontent.com/assets/14918821/10809760/39a08c76-7e2c-11e5-8d1b-c54e10a2eac3.png)

**Comment by nf-dj** [comment]
fix here: https://github.com/nfco/netforce/commit/8d3db64b2b2ddb73a9573c9f186381c70561f772
