### ISSUE TITLE
Can't Post suptype Prepayment 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#47]
http://umgkh.netforce.com/ui#name=payment&active_id=5190&mode=form&search_condition=%5B%5B%22number%22%2C%22ilike%22%2C%22RV%2F2015%2F060%22%5D%5D
Error Duplicate keys: model=account.invoice, company_id='5', number='None'

![image](https://cloud.githubusercontent.com/assets/14918821/10959930/1f790762-83b1-11e5-9171-9e216cb48ff1.png)

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/3fcd1e9630b8afa7caf744d04a9993f685ede2f1
