### ISSUE TITLE
In the list view for journal entry, cloud you Add one more tab called "Voided" 

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#52]
because user can't find journal status "Voided".

![image](https://cloud.githubusercontent.com/assets/14918821/11086875/ef439f68-8887-11e5-98f1-0a9dd4131f41.png)

**Comment by sidzan** [comment]
They can search from the search button.

On Wed, Nov 11, 2015 at 3:24 PM, Rattanawan-t <notifications@github.com>
wrote:

> because user can't find journal status "Voided".
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/14918821/11086875/ef439f68-8887-11e5-98f1-0a9dd4131f41.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfco/netforce/issues/52>.
>



-- 
Regards ,
Sijan shrestha

**Comment by sidzan** [comment]
example
​

On Wed, Nov 11, 2015 at 3:27 PM, Sijan Shrestha <sijan.s@netforce.com>
wrote:

> They can search from the search button.
>
> On Wed, Nov 11, 2015 at 3:24 PM, Rattanawan-t <notifications@github.com>
> wrote:
>
>> because user can't find journal status "Voided".
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/14918821/11086875/ef439f68-8887-11e5-98f1-0a9dd4131f41.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nfco/netforce/issues/52>.
>>
>
>
>
> --
> Regards ,
> Sijan shrestha
>



-- 
Regards ,
Sijan shrestha

**Comment by songpon** [comment]
In my opinion , journal entry should have no void ( cancel status )
It should be only draft and  posted 
for ex.
Create and revert ( both is posted ) 
should not allow cancel status , for Revenue Department will not certify.
So, cancellation can use the same meaning as revert.

**Comment by nf-dj** [comment]
in old version 2.x, used to have "voided" tab already. (in xero accounting program, it also has voided tab)
Songpon, are you sure that if put that tab again it is against revenue dept rules?

**Comment by nf-dj** [comment]
I updated to show JE status in search form. (so can filter from that form)
But didn't included "voided" tab to reduce number of tabs.
