### ISSUE TITLE
Sequence number at payment not working when switch other sequence

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#67]
![image](https://cloud.githubusercontent.com/assets/14918821/11414833/fa4d1adc-942c-11e5-9e2e-410924937e0f.png)

![image](https://cloud.githubusercontent.com/assets/14918821/11414836/0a492066-942d-11e5-916a-3519d4e7d049.png)

**Comment by Rattanawan-t** [comment]
Date of October but sequence show month of november

**Comment by nf-dj** [comment]
fix: https://github.com/nfco/netforce/commit/3fe8116b6e65cc5bed2d81209f0e6badc1619ff6
