### ISSUE TITLE
Link to invoice not correct.

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#68]
When click arrow for link to invoice(AR) but it link to credit note invoice. Actually, this is invoice not credit note

![image](https://cloud.githubusercontent.com/assets/14918821/11417615/136633d2-944b-11e5-9d1f-1e5a82f66dbb.png)

![image](https://cloud.githubusercontent.com/assets/14918821/11417636/2e6455f6-944b-11e5-9970-85960b872d1c.png)

**Comment by songpon** [comment]
this one get default view for model , it have to support get view also in related fields

**Comment by nf-dj** [comment]
Fixed in this commit: https://github.com/nfco/netforce/commit/d1a09f277e1ff70548821771af2cd9ce35422354
(added priority field in action, used by find_details_action function)
