### ISSUE TITLE
Cost Price (Cur) not automatic compute at Good Receipt.

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#7]

**Comment by Rattanawan-t** [comment]
![image](https://cloud.githubusercontent.com/assets/14918821/10728902/5c99ad7c-7c18-11e5-9f45-d76ed006a4b8.png)

![image](https://cloud.githubusercontent.com/assets/14918821/10728917/6dd061a8-7c18-11e5-921c-c84004825616.png)

**Comment by nf-dj** [comment]
fix here: https://github.com/nfco/netforce/commit/338e1da191927f51c840aa2130167468374e490a
