### ISSUE TITLE
mention the contact information in journal entry

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#74]
For the direct payment, if the payment line use account  in Group 1 and 2 (Asset and Liability). After post to journal entry, system should mention the contact information in Journal Entry created.

![image](https://cloud.githubusercontent.com/assets/14918821/11581138/4738e0a2-9a71-11e5-893e-87dd778665d4.png)
![image](https://cloud.githubusercontent.com/assets/14918821/11581145/5b782ff0-9a71-11e5-9841-4493e57af85d.png)

**Comment by songpon** [comment]
direct payment no payable/receivable

**Comment by bank-netforce** [comment]
for all payment method or just Direct Payment?

**Comment by bank-netforce** [comment]
Done on 31 March 2016
