### ISSUE TITLE
Fix number prepayment at invoice AP and AR

### ISSUE THREAD

**Issue by Rattanawan-t** [nfco/netforce#93]
- We already create prepayment at payment menu and after post prepayment should not create number again at Sale invoice and Purchased invoice also.
- When Allocate credit invoice prepayment should show number of prepayment (from menu payment)
![image](https://cloud.githubusercontent.com/assets/14918821/11714179/e3406742-9f6a-11e5-9fb4-2bf47a113533.png)

![image](https://cloud.githubusercontent.com/assets/14918821/11714191/0575aa34-9f6b-11e5-8b48-9c3c19af7bda.png)

![image](https://cloud.githubusercontent.com/assets/14918821/11714249/6175d624-9f6b-11e5-8d31-9bc503535605.png)

**Comment by nf-dj** [comment]
fixed in https://github.com/nfco/netforce/commit/422eb7ad6b03ecfe5ec61966271dfcdeb8977115
